"""

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.core.urlresolvers import reverse_lazy
from celery.schedules import crontab

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*y**dxboh!u)*_fxu@s%^1)n$)*3o=v2^w$ld%1k-a%$s4f5mt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'pipeline',
    'crispy_forms',

    'common',
    'user',

    'rest_framework',
    'example',
    'subject'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'recordnote.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'recordnote.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

PG_NAME = 'record'
PG_USER = 'record'
PG_PASSWORD = 'record'
PG_HOST = 'localhost'
PG_PORT = '5432'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': PG_NAME,
        'USER': PG_USER,
        'PASSWORD': PG_PASSWORD,
        'HOST': PG_HOST,
        'PORT': PG_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'cs-CZ'

TIME_ZONE = 'Europe/Prague'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'


STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',
)
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'


PIPELINE = {
    'STYLESHEETS': {
        'bootstrap': {
            'source_filenames': (
                '3rd/bootstrap-3.3.5/less/bootstrap.less',
            ),
            'output_filename': 'css/b.css',
            'extra_context': {
                'media': 'screen,projection',
            },
        },
        'recordnote': {
            'source_filenames': (
                'recordnote/common.less',
                '3rd/jquery-ui-1.12.0.custom/jquery-ui.min.css',
            ),
            'output_filename': 'css/k.css',
            'extra_context': {
                'media': 'screen,projection',
            },

        }
    },
    'JAVASCRIPT': {
        'jquery': {
            'source_filenames': (
                '3rd/jquery-2.1.4/jquery-2.1.4.min.js',
                '3rd/jquery-ui-1.12.0.custom/jquery-ui.min.js',
            ),
            'output_filename': 'js/jq.js',

        },
        'bootstrap': {
            'source_filenames': (
                '3rd/bootstrap-3.3.5/js/transition.js',
                '3rd/bootstrap-3.3.5/js/modal.js',
                '3rd/bootstrap-3.3.5/js/dropdown.js',
                '3rd/bootstrap-3.3.5/js/scrollspy.js',
                '3rd/bootstrap-3.3.5/js/tab.js',
                '3rd/bootstrap-3.3.5/js/tooltip.js',
                '3rd/bootstrap-3.3.5/js/popover.js',
                '3rd/bootstrap-3.3.5/js/alert.js',
                '3rd/bootstrap-3.3.5/js/button.js',
                '3rd/bootstrap-3.3.5/js/collapse.js',
                '3rd/bootstrap-3.3.5/js/carousel.js',
                '3rd/bootstrap-3.3.5/js/affix.js',
            ),
            'output_filename': 'js/b.js',
        },
    }
}

PIPELINE['COMPILERS'] = (
    'pipeline.compilers.less.LessCompiler',
)


CRISPY_TEMPLATE_PACK = 'bootstrap3'

AUTH_USER_MODEL = 'user.User'
LOGIN_URL = reverse_lazy('user:login')
LOGOUT_URL = reverse_lazy('user:logout')
LOGIN_REDIRECT_URL = reverse_lazy('user:list')


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'user.auth.ApiAuth',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 300,
}


BROKER_URL = 'redis://127.0.0.1:6379/10'
CELERY_TIMEZONE = 'UTC' # timezone caused many confusing issues
CELERY_TRACK_STARTED = True
CELERY_IGNORE_RESULT = True
CELERY_RESULT_BACKEND = 'db+postgresql://%s:%s@%s:%s/%s' % (PG_USER, PG_PASSWORD, PG_HOST, PG_PORT, PG_NAME)

# # automaticky o 4:00 vymazava vysledky uloh pokial nieje None
CELERY_TASK_RESULT_EXPIRES = None

# CELERYBEAT_SCHEDULE = {
#     'start_period_payments': {
#         'task': 'common.tasks.test_task_periodic',
#         'schedule': crontab(),
#     },
# }

# EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'

# pripojenie na stt (
API_STT_BASE_URI = 'http://77.240.177.148:8601'
API_STT_AUTH = ('team1', 'hackathon')
