# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 20:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000000)),
                ('stt_output', django.contrib.postgres.fields.jsonb.JSONField()),
                ('result_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject'),
        ),
        migrations.AddField(
            model_name='record',
            name='tape',
            field=models.ManyToManyField(to='subject.Tape'),
        ),
        migrations.AddField(
            model_name='event',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Record'),
        ),
        migrations.AddField(
            model_name='event',
            name='subject',
            field=models.ManyToManyField(to='subject.Subject'),
        ),
    ]
