# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='record',
        ),
        migrations.RemoveField(
            model_name='record',
            name='tape',
        ),
        migrations.AddField(
            model_name='record',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tape',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.Record'),
            preserve_default=False,
        ),
    ]
