# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-07 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20180406_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
