# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 17:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
from example.models import Example


def CreateExampleData(apps, schema_editor):
    Example(name="Django Reinhardtovi", code="gypsy-jazz", note="Framework byl pojmenován po jazzovém kytaristovi Django Reinhardtovi.", base=True).save()
    Example(name="Don’t Repeat Yourself", code="DRY", note="Zaměřuje se na znovupoužitelnost a propojitelnost komponent rychlý vývoj.", base=True).save()
    Example(name="PostgreSQL", code="Postgre", note="", base=True).save()

    Example(name="Generator Rand", code="gen", note="", base=True).save()
    Example(name="Jindřich Brůha", code="gen2", note="", base=True).save()
    Example(name="Teodor Pavlát", code="gen3", note="", price=500).save()
    Example(name="Kristián Větrovský", code="gen4", note="", price=20).save()
    Example(name="Boris Češka", code="gen5", note="", price=1000).save()
    Example(name="Štěpán Slavíček", code="gen6", note="", price=0).save()
    Example(name="Prokop Šerý", code="gen7", note="").save()


def RemoveExampleData(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='jméno a příjmení')),
                ('code', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_-]+$')], verbose_name='kód')),
                ('note', models.TextField(blank=True, verbose_name='poznámka')),
                ('base', models.BooleanField(default=False, verbose_name='hlavni')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='cena')),
            ],
        ),
        migrations.RunPython(CreateExampleData, RemoveExampleData),
    ]
